
name: 'Release'

on:
  workflow_dispatch:
    inputs:
      mark_prerelease:
        description: 'Mark as a pre-release?'
        required: true
        default: 'false'
        type: boolean
      publish_to_aur:
        description: 'Publish to AUR?'
        required: false
        default: 'true'
        type: boolean
      publish_to_snap:
        description: 'Publish to Snapcraft?'
        required: false
        default: 'false'
        type: boolean
jobs:
  generate_version_and_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.changelog.outputs.new_version }}
      changelog: ${{ steps.changelog.outputs.clean_changelog }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'
          skip-commit: 'true'
          skip-tag: 'true'

  build_and_release:
    needs: generate_version_and_changelog
    if: needs.generate_version_and_changelog.outputs.skipped == 'false'
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Update version files
        run: |
          npm version ${{ needs.generate_version_and_changelog.outputs.new_version }} --no-git-tag-version
          sed -i'' 's/"version": ".*"/"version": "${{ needs.generate_version_and_changelog.outputs.new_version }}"/' src-tauri/tauri.conf.json

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      - name: Build and Release with Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 'v${{ needs.generate_version_and_changelog.outputs.new_version }}'
          releaseName: 'VeloDown v${{ needs.generate_version_and_changelog.outputs.new_version }}'
          releaseBody: ${{ needs.generate_version_and_changelog.outputs.changelog }}
          releaseDraft: false
          prerelease: ${{ inputs.mark_prerelease }}
          # This tells tauri-action to commit the changed package.json/tauri.conf.json
          args: '--no-dev-path --no-debug'


  deploy:
    needs: build_and_release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AUR Publish
        if: ${{ inputs.publish_to_aur == true }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'aur-publish.yml',
              ref: 'main',
              inputs: {
                version_name: '${{ needs.build_and_release.outputs.appVersion }}'
              }
            });

      # - name: Trigger Snapcraft Publish
      #   if: ${{ inputs.publish_to_snap == true }}
        # run: echo "Create the yml file first."
