name: 'Release'

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Release version (e.g., 0.2.0). This must be a new version.'
        required: true
      mark_prerelease:
        description: 'Mark as a pre-release?'
        required: true
        default: 'false'
        type: boolean
      publish_to_aur:
        description: 'Publish to AUR?'
        required: false
        default: 'true'
        type: boolean

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ inputs.version_name }}
      release_notes: ${{ steps.generate_notes.outputs.release-notes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: generate_notes
        uses: mlm-games/release-notes-generator@v1.1.0 # Using the action you provided
        with:
          version: ${{ inputs.version_name }}
          changelog-path: 'CHANGELOG.md'
          auto-commit: 'false' 
          exclude-patterns: 'chore(release),Merge pull request'

      - name: Update version files
        run: |
          echo "Bumping versions to ${{ inputs.version_name }}"
          npm version ${{ inputs.version_name }} --no-git-tag-version
          sed -i'' 's/"version": ".*"/"version": "${{ inputs.version_name }}"/' src-tauri/tauri.conf.json
      
      - name: Commit, Tag, and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(release): Bump version to ${{ inputs.version_name }}'
          tagging_message: 'v${{ inputs.version_name }}'
          push_options: '--follow-tags'

  build_tauri:
    needs: prepare_release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository at new tag
        uses: actions/checkout@v4
        with:
          ref: 'v${{ needs.prepare_release.outputs.version }}'

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      - name: Build with Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '--no-dev-path --no-debug'

  create_github_release:
    needs: [prepare_release, build_tauri]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: tauri-artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v${{ needs.prepare_release.outputs.version }}'
          name: 'VeloDown v${{ needs.prepare_release.outputs.version }}'
          # use the generated changelog from the first job as the release body
          body: ${{ needs.prepare_release.outputs.release_notes }}
          prerelease: ${{ inputs.mark_prerelease }}
          files: tauri-artifacts/*/*

  deploy:
    needs: create_github_release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AUR Publish
        if: ${{ inputs.publish_to_aur == true }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'aur-publish.yml',
              ref: 'main',
              inputs: {
                version_name: '${{ needs.prepare_release.outputs.version }}'
              }
            });

      # - name: Trigger Snapcraft Publish
      #   if: ${{ inputs.publish_to_snap == true }}
        # run: echo "Create the yml file first."
