
name: 'Publish Release'

# This action triggers on every push to a branch named `release`.
# To use this, you would work on `main`, and when you are ready to
# release a new version, you would merge `main` into `release` and push.
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest Long-Term Support version of Node.js

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The name of the tag for the release. The action will replace `__VERSION__`
          # with the version from your `src-tauri/tauri.conf.json`.
          tagName: 'v__VERSION__'

          releaseName: 'VeloDown v__VERSION__'

          releaseBody: 'New release of VeloDown. Download the installer for your OS below.'

          releaseDraft: false

          prerelease: true
