
name: 'Release'

on:
  workflow_dispatch:
    inputs:
      mark_prerelease:
        description: 'Mark as a pre-release? (true/false)'
        required: true
        default: 'false'
        type: boolean
      publish_to_aur:
        description: 'Publish to AUR?'
        required: false
        default: 'true'
        type: boolean
      publish_to_snap:
        description: 'Publish to Snapcraft?'
        required: false
        default: 'false'
        type: boolean

jobs:
  version-and-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.changelog.outputs.new_version }}
      new_tag: ${{ steps.changelog.outputs.tag }}
      changelog: ${{ steps.changelog.outputs.clean_changelog }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'

      - name: Update tauri.conf.json version
        if: steps.changelog.outputs.skipped == 'false'
        run: |
          echo "New version from changelog action: ${{ steps.changelog.outputs.new_version }}"
          sed -i 's/"version": ".*"/"version": "${{ steps.changelog.outputs.new_version }}"/' src-tauri/tauri.conf.json
          echo "Updated tauri.conf.json"

      - name: Commit and Push Version Changes
        if: steps.changelog.outputs.skipped == 'false'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(release): Bump version to ${{ steps.changelog.outputs.new_version }}'
          push_options: '--force --tags'

  build-and-release:
    needs: version-and-changelog
    if: needs.version-and-changelog.outputs.new_version != ''
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ needs.version-and-changelog.outputs.new_tag }}
          releaseName: 'VeloDown ${{ needs.version-and-changelog.outputs.new_tag }}'
          releaseBody: ${{ needs.version-and-changelog.outputs.changelog }}
          releaseDraft: false
          prerelease: ${{ inputs.mark_prerelease }}

  deploy:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: needs.version-and-changelog.outputs.new_version != ''
    steps:
      - name: Trigger AUR Publish
        if: ${{ inputs.publish_to_aur == true }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'aur-publish.yml',
              ref: 'main',
              inputs: {
                version_name: '${{ needs.version-and-changelog.outputs.new_version }}'
              }
            });

      # - name: Trigger Snapcraft Publish
      #   if: ${{ inputs.publish_to_snap == true }}
        # run: echo "Create the yml file first."
